# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ce05496695d19ee95b850394e476d0a0c71324bd154cf5fa2ebfd2a62b529027c1875cc8d64085187b419de72eff9e84f1353084d430ccfdc8b690f625b6864

test:
  secret_key_base: f94068a3dde4ace04dc42d1d867b75547dd88ec007bb9c75fde39c0065863dd0272b05e615d7f616bd6a5b6ee4794ac19b6c83be74714301fb1b30af843118a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
